title: Florian's Blog
tagline: A blog about technology and programming
description: Florian's personal blog where he shares insights and tutorials on various tech topics.
logo: /favicon.png
logo_large: /assets/images/logo_white.png
url: https://blog.floriang.dev

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/floriang.png

show_excerpts: true
excerpt_separator: <!--more-->

author:
  name: "Florian Gross"
  twitter: gro_lp
  github: FlorianGross
  linkedin: floriangross

twitter:
  username: gro_lp
  card: summary

theme: minima
minima:
  skin: solarized-dark
  social_links:
    -  title: "GitHub: FlorianGross"
       icon: github
       url: "https://github.com/FlorianGross"
    - title: "X: @gro_lp"
      icon: x-twitter
      url: "https://x.com/gro_lp"
    - title: "LinkedIn: floriangdev"
      icon: linkedin
      url: "https://www.linkedin.com/in/floriangdev/"

kramdown:
  toc_levels: 2..2

sass:
  style: compressed

safe: true
whitelist:
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-github-metadata
 - jekyll-relative-links
 - jemoji
plugins:
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-github-metadata
 - jekyll-relative-links
 - jemoji

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'CNAME'
  - '.git/'
  - '.vs/'
  - '*.TMP'
  - '*.sh'
  - '*.ps1'
  - 'vendor'
